[package]
name = "password-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
rand = "0.9.2"
aes-gcm = "0.10.3"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
base64 = "0.22.1"
